### ISSUE TITLE
Does not work with storybook 3.2.3

### ISSUE THREAD

**Issue by davidmason** [evgenykochetkov/react-storybook-addon-props-combinations#19]
I tried to use this plugin, configured as per the readme with `setAddon`, but it fails with the error shown below. It looks like the API for registering addons has changed since this was written, so it probably needs an update.

`@storybook/react` 3.2.3
react-storybook-addon-props-combinations 0.4.1

```stacktrace
TypeError: (0 , _react3.storiesOf)(...).addWithPropsCombinations is not a function
    at Object.eval (webpack:///./app/components/Icon/Icon.story.js?:48:2)
    at eval (webpack:///./app/components/Icon/Icon.story.js?:52:30)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:8980:1)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:670:30)
    at fn (http://localhost:9001/static/preview.bundle.js:88:20)
    at eval (webpack:///./app/components/components.story.js?:18:1)
    at Object.<anonymous> (http://localhost:9001/static/preview.bundle.js:7004:1)
    at __webpack_require__ (http://localhost:9001/static/preview.bundle.js:670:30)
    at fn (http://localhost:9001/static/preview.bundle.js:88:20)
    at loadStories (webpack:///./.storybook-frontend/config.js?:64:3)
```

**Comment by evgenykochetkov** [comment]
Yep, totally needs an update. I'll release it this weekend.

**Comment by davidmason** [comment]
Great! I was looking at whether I could update it, but couldn't see docs for the old addon API to figure out what changes would be needed.

**Comment by davidmason** [comment]
This would work without a custom `add` function, so it could just export `withPropsCombinations`. You just would not be able to set default options, but it would be a start.

```
import { withPropsCombinations } from 'react-storybook-addon-props-combinations'
import propsCombinationsOptions from 'my-props-combinations-options'

storiesOf('MyComponent', module)
  .add('props combinations', () => withPropsCombinations(
    MyComponent,
    { fancy: [true, false], className: ['', 'small', 'medium', 'large', 'jumboriffic'] },
    propsCombinationsOptions
  ))
```

You wouldn't get the

**Comment by evgenykochetkov** [comment]
Sorry for the big delay!
Upgraded for storybook 3.x and published as v1.0.0
